#' Fetch NA-POPS modelling results
#'
#' \code{fetch_data} downloads all coefficients and covariance matrices
#' generated by NA-POPS models. A package-specific directory is created on the user's
#' computer (see documentation of \code{rappdirs::appdir} for details of where this
#' directory lives), and NA-POPS data is saved to that directory for use by other functions.
#'
#' @param quiet Logical: should download progress be suppressed? Defaults to TRUE
#'
#' @importFrom rappdirs app_dir
#' @importFrom utils download.file
#'
#' @return None
#'
#' @export
#'

fetch_data <- function(quiet = TRUE)
{
  # Create napops directory on disk
  napops_dir <- rappdirs::app_dir(appname = "napops")

  if (isFALSE(file.exists(napops_dir$data())))
  {
    message(paste0("Creating data directory at ", napops_dir$data()))
    dir.create(napops_dir$data(), recursive = TRUE)
  }else
  {
    message(paste0("Using data directory at ", napops_dir$data()))
  }

  # Download distance coefficients
  download.file("https://raw.githubusercontent.com/na-pops/results/master/coefficients/distance.csv",
                destfile = paste0(napops_dir$data(), "/distance.csv"),
                method = "curl",
                quiet = quiet)

  # Download distance covariance
  download.file("https://raw.githubusercontent.com/na-pops/results/master/var-covar/dis_vcv_list.rda",
                destfile = paste0(napops_dir$data(), "/dis_vcv.rda"),
                method = "curl",
                quiet = quiet)

  # Download removal coefficients
  download.file("https://raw.githubusercontent.com/na-pops/results/master/coefficients/removal.csv",
                destfile = paste0(napops_dir$data(), "/removal.csv"),
                method = "curl",
                quiet = quiet)

  # Download removal covariance
  download.file("https://raw.githubusercontent.com/na-pops/results/master/var-covar/rem_vcv_list.rda",
                destfile = paste0(napops_dir$data(), "/rem_vcv.rda"),
                method = "curl",
                quiet = quiet)
}
